basic:
    name: app.go-solid.be
    environments:
        production: 'https://app.go-solid.be'
        staging: 'https://staging.app.go-solid.be'
        development: ''
    breakpoints:
        - 480
        - 1024
        - 1200
    pages:
        - /nl
        - /nl/user/login
        - /nl/dashboard
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - null
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 30
    night_mode: ''
    retina_images: ''
    login:
        type: ''
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: false
proxy: false
type: single-site
